{
    "links": [],
    "content": [
        {
            "dmobscd": "1001210",
            "obsnm": "광동댐",
            "agcnm": "한국수자원공사",
            "addr": "강원도 삼척시",
            "etcaddr": "숙암리 15",
            "lon": "128-56-48",
            "lat": "37-20-40 ",
            "pfh": "675.3",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "1003110",
            "obsnm": "충주댐",
            "agcnm": "한국수자원공사",
            "addr": "충청북도 충주시",
            "etcaddr": "종민동",
            "lon": "127-59-44",
            "lat": "37-00-13 ",
            "pfh": "145",
            "fldlmtwl": "138",
            "links": []
        },
        {
            "dmobscd": "1003611",
            "obsnm": "충주조정지댐",
            "agcnm": "한국수자원공사",
            "addr": "충청북도 충주시",
            "etcaddr": "가금면 장천리",
            "lon": "127-52-00",
            "lat": "37-02-41 ",
            "pfh": "67.3",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "1004310",
            "obsnm": "괴산댐",
            "agcnm": "한국수력원자력",
            "addr": "충청북도 괴산군",
            "etcaddr": "칠성면 산막이옛길 43",
            "lon": "127-50-42",
            "lat": "36-45-45 ",
            "pfh": "136.93",
            "fldlmtwl": "134",
            "links": []
        },
        {
            "dmobscd": "1006110",
            "obsnm": "횡성댐",
            "agcnm": "한국수자원공사",
            "addr": "강원도 횡성군",
            "etcaddr": "갑천면 대관대리",
            "lon": "128-01-57",
            "lat": "37-32-42 ",
            "pfh": "180",
            "fldlmtwl": "178.2",
            "links": []
        },
        {
            "dmobscd": "1009710",
            "obsnm": "평화의댐",
            "agcnm": "한국수자원공사",
            "addr": "강원도 화천군",
            "etcaddr": "화천읍 수하리",
            "lon": "127-50-55",
            "lat": "38-12-43 ",
            "pfh": "264.6",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "1010310",
            "obsnm": "화천댐",
            "agcnm": "한국수력원자력",
            "addr": "강원도 화천군",
            "etcaddr": "간동면 어룡동길 42",
            "lon": "127-46-44",
            "lat": "38-07-04 ",
            "pfh": "183",
            "fldlmtwl": "175",
            "links": []
        },
        {
            "dmobscd": "1010320",
            "obsnm": "춘천댐",
            "agcnm": "한국수력원자력",
            "addr": "강원도 춘천시",
            "etcaddr": "신북읍 영서로 3741",
            "lon": "127-40-15",
            "lat": "37-58-00 ",
            "pfh": "104.9",
            "fldlmtwl": "102",
            "links": []
        },
        {
            "dmobscd": "1012110",
            "obsnm": "소양강댐",
            "agcnm": "한국수자원공사",
            "addr": "강원도 춘천시",
            "etcaddr": "동면 월곡리",
            "lon": "127-48-44",
            "lat": "37-56-46 ",
            "pfh": "198",
            "fldlmtwl": "190.3",
            "links": []
        },
        {
            "dmobscd": "1013310",
            "obsnm": "의암댐",
            "agcnm": "한국수력원자력",
            "addr": "강원도 춘천시",
            "etcaddr": "신동면 옛경춘로 62-15",
            "lon": "127-40-33",
            "lat": "37-50-12 ",
            "pfh": "73.36",
            "fldlmtwl": "70.5",
            "links": []
        },
        {
            "dmobscd": "1015310",
            "obsnm": "청평댐",
            "agcnm": "한국수력원자력",
            "addr": "경기도 가평군",
            "etcaddr": "설악면 유명로 2630",
            "lon": "127-25-16",
            "lat": "37-43-31 ",
            "pfh": "52",
            "fldlmtwl": "50",
            "links": []
        },
        {
            "dmobscd": "1017310",
            "obsnm": "팔당댐",
            "agcnm": "한국수력원자력",
            "addr": "경기도 남양주시",
            "etcaddr": "조안면 다산로 320",
            "lon": "127-17-05",
            "lat": "37-31-30 ",
            "pfh": "27",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "1021701",
            "obsnm": "군남댐",
            "agcnm": "한국수자원공사",
            "addr": "경기도 연천군",
            "etcaddr": "군남면 선곡리 606-2",
            "lon": "127-00-57",
            "lat": "38-06-18 ",
            "pfh": "40",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "1022701",
            "obsnm": "한탄강댐",
            "agcnm": "한국수자원공사",
            "addr": "경기도 연천군",
            "etcaddr": "연천읍 고문리",
            "lon": "127-08-00",
            "lat": "38-03-50 ",
            "pfh": "114.4",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "1302210",
            "obsnm": "달방댐",
            "agcnm": "한국수자원공사",
            "addr": "강원도 동해시",
            "etcaddr": "삼화동 산284",
            "lon": "129-02-16",
            "lat": "37-30-17 ",
            "pfh": "114.25",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2001110",
            "obsnm": "안동댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 안동시",
            "etcaddr": "성곡동",
            "lon": "128-46-26",
            "lat": "36-35-06 ",
            "pfh": "161.7",
            "fldlmtwl": "160",
            "links": []
        },
        {
            "dmobscd": "2001611",
            "obsnm": "안동댐조정지",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 안동시",
            "etcaddr": "상아동",
            "lon": "128-44-55",
            "lat": "36-34-01 ",
            "pfh": "98.8",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2002110",
            "obsnm": "임하댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 안동시",
            "etcaddr": "임하면 임하리",
            "lon": "128-52-60",
            "lat": "36-32-16 ",
            "pfh": "164.7",
            "fldlmtwl": "161.7",
            "links": []
        },
        {
            "dmobscd": "2002111",
            "obsnm": "성덕댐",
            "agcnm": "한국수자원공사",
            "addr": "경북 청송군 안덕면 성재리",
            "etcaddr": " ",
            "lon": "128-57-55",
            "lat": "36-14-26 ",
            "pfh": "364.9",
            "fldlmtwl": "362",
            "links": []
        },
        {
            "dmobscd": "2002610",
            "obsnm": "임하댐조정지",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 안동시",
            "etcaddr": "임하면 천전리",
            "lon": "128-50-45",
            "lat": "36-32-06 ",
            "pfh": "106.2",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2004101",
            "obsnm": "영주댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 영주시",
            "etcaddr": "평은면",
            "lon": "128-39-21",
            "lat": "36-43-21 ",
            "pfh": "164",
            "fldlmtwl": "156.7",
            "links": []
        },
        {
            "dmobscd": "2008110",
            "obsnm": "군위댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 군위군",
            "etcaddr": "고로면 학성리 407번지",
            "lon": "128-47-38",
            "lat": "36-07-14 ",
            "pfh": "205.1",
            "fldlmtwl": "204",
            "links": []
        },
        {
            "dmobscd": "2010101",
            "obsnm": "김천부항댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 김천시",
            "etcaddr": "부항면 신옥리",
            "lon": "128-00-20",
            "lat": "35-58-56 ",
            "pfh": "198.6",
            "fldlmtwl": "193.5",
            "links": []
        },
        {
            "dmobscd": "2012101",
            "obsnm": "보현산댐",
            "agcnm": "한국수자원공사",
            "addr": "경북 영천시 화북면 입석리",
            "etcaddr": " ",
            "lon": "128-56-57",
            "lat": "36-07-34 ",
            "pfh": "238.5",
            "fldlmtwl": "236",
            "links": []
        },
        {
            "dmobscd": "2012210",
            "obsnm": "영천댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 영천시",
            "etcaddr": "자양면 성곡리",
            "lon": "129-00-44",
            "lat": "36-03-49 ",
            "pfh": "159.3",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2015110",
            "obsnm": "합천댐",
            "agcnm": "한국수자원공사",
            "addr": "경상남도 합천군",
            "etcaddr": "대병면 상천리",
            "lon": "128-01-54",
            "lat": "35-32-02 ",
            "pfh": "179",
            "fldlmtwl": "176",
            "links": []
        },
        {
            "dmobscd": "2018110",
            "obsnm": "남강댐",
            "agcnm": "한국수자원공사",
            "addr": "경상남도 진주시",
            "etcaddr": "판문동",
            "lon": "128-02-13",
            "lat": "35-09-53 ",
            "pfh": "46",
            "fldlmtwl": "41",
            "links": []
        },
        {
            "dmobscd": "2018611",
            "obsnm": "합천댐조정지",
            "agcnm": "한국수자원공사",
            "addr": "경상남도 합천군",
            "etcaddr": "용주면 내가리",
            "lon": "128-05-05",
            "lat": "35-32-25 ",
            "pfh": "65.5",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2021110",
            "obsnm": "밀양댐",
            "agcnm": "한국수자원공사",
            "addr": "경상남도 밀양시",
            "etcaddr": "단장면 고례리",
            "lon": "128-55-55",
            "lat": "35-28-58 ",
            "pfh": "210.2",
            "fldlmtwl": "207.2",
            "links": []
        },
        {
            "dmobscd": "2021210",
            "obsnm": "운문댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 청도군",
            "etcaddr": "운문면 대천리",
            "lon": "128-54-57",
            "lat": "35-43-19 ",
            "pfh": "152.6",
            "fldlmtwl": " ",
            "links": []
        },
        null,
        null,
        null,
        {
            "dmobscd": "2201231",
            "obsnm": "대곡댐",
            "agcnm": "한국수자원공사",
            "addr": "울산광역시 울주군 두동면 천전리",
            "etcaddr": " ",
            "lon": "129-10-30",
            "lat": "35-37-06 ",
            "pfh": "122.7",
            "fldlmtwl": "120",
            "links": []
        },
        null,
        {
            "dmobscd": "2301211",
            "obsnm": "회야댐",
            "agcnm": null,
            "addr": "울산광역시 울주군",
            "etcaddr": "웅촌면 통천리 44",
            "lon": "129-16-31",
            "lat": "35-28-10 ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2403201",
            "obsnm": "감포댐",
            "agcnm": "한국수자원공사",
            "addr": "경상북도 경주시 감포읍 오류리",
            "etcaddr": " ",
            "lon": "129-30-38",
            "lat": "35-50-07 ",
            "pfh": "41.2",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "2503210",
            "obsnm": "연초댐",
            "agcnm": "한국수자원공사",
            "addr": "경상남도 거제시 연초면 덕치리",
            "etcaddr": " ",
            "lon": "128-39-60",
            "lat": "34-56-25 ",
            "pfh": "49.6",
            "fldlmtwl": "48",
            "links": []
        },
        {
            "dmobscd": "2503220",
            "obsnm": "구천댐",
            "agcnm": "한국수자원공사",
            "addr": "경상남도 거제시",
            "etcaddr": "동부면 구천리",
            "lon": "128-38-11",
            "lat": "34-49-20 ",
            "pfh": "94.54",
            "fldlmtwl": "93",
            "links": []
        },
        {
            "dmobscd": "3001110",
            "obsnm": "용담댐",
            "agcnm": "한국수자원공사",
            "addr": "전라북도 진안군 안천면",
            "etcaddr": "삼락리",
            "lon": "127-31-44",
            "lat": "35-56-30 ",
            "pfh": "265.5",
            "fldlmtwl": "261.5",
            "links": []
        },
        null,
        {
            "dmobscd": "3008110",
            "obsnm": "대청댐",
            "agcnm": "한국수자원공사",
            "addr": "대전광역시 대덕구",
            "etcaddr": "미호동",
            "lon": "127-28-50",
            "lat": "36-28-43 ",
            "pfh": "80",
            "fldlmtwl": "76.5",
            "links": []
        },
        {
            "dmobscd": "3008611",
            "obsnm": "대청댐조정지",
            "agcnm": "한국수자원공사",
            "addr": "대전시 대덕구",
            "etcaddr": "용호동 천426-1",
            "lon": "127-27-08",
            "lat": "36-26-59 ",
            "pfh": "35.1",
            "fldlmtwl": "30",
            "links": []
        },
        {
            "dmobscd": "3014410",
            "obsnm": "금강하구둑",
            "agcnm": "한국농어촌공사",
            "addr": "전라북도 군산시",
            "etcaddr": "성산면 성덕리",
            "lon": "126-45-06",
            "lat": "36-00-49 ",
            "pfh": "4.62",
            "fldlmtwl": " ",
            "links": []
        },
        null,
        null,
        {
            "dmobscd": "3203310",
            "obsnm": "보령댐",
            "agcnm": "한국수자원공사",
            "addr": "충청남도 보령시",
            "etcaddr": "미산면 용수리",
            "lon": "126-38-55",
            "lat": "36-14-59 ",
            "pfh": "75.5",
            "fldlmtwl": "74",
            "links": []
        },
        {
            "dmobscd": "3301651",
            "obsnm": "구이",
            "agcnm": "한국농어촌공사",
            "addr": "전라북도 완주군",
            "etcaddr": "구이면 두현리 30",
            "lon": "127-07-29",
            "lat": "35-44-23 ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        null,
        {
            "dmobscd": "4001110",
            "obsnm": "섬진강댐",
            "agcnm": "한국수자원공사",
            "addr": "전라북도 임실군",
            "etcaddr": "강진면 용수리",
            "lon": "127-06-49",
            "lat": "35-32-22 ",
            "pfh": "197.7",
            "fldlmtwl": "194",
            "links": []
        },
        {
            "dmobscd": "4007110",
            "obsnm": "주암댐",
            "agcnm": "한국수자원공사",
            "addr": "전라남도 순천시",
            "etcaddr": "주암면 대광리",
            "lon": "127-14-21",
            "lat": "35-03-33 ",
            "pfh": "110.5",
            "fldlmtwl": "108.5",
            "links": []
        },
        null,
        null,
        null,
        null,
        null,
        null,
        {
            "dmobscd": "5001410",
            "obsnm": "광주댐",
            "agcnm": "한국농어촌공사",
            "addr": "전라남도 담양군",
            "etcaddr": "고서면 분향리 광주댐내",
            "lon": "126-59-22",
            "lat": "35-11-60 ",
            "pfh": "79.85",
            "fldlmtwl": "75.6",
            "links": []
        },
        {
            "dmobscd": "5001420",
            "obsnm": "담양댐",
            "agcnm": "한국농어촌공사",
            "addr": "전라남도 담양군",
            "etcaddr": "용면 도림리 취수탑 도교",
            "lon": "127-00-46",
            "lat": "35-22-37 ",
            "pfh": "124.36",
            "fldlmtwl": "121.9",
            "links": []
        },
        {
            "dmobscd": "5001600",
            "obsnm": "담양3조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "5001604",
            "obsnm": "담양2조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "5001608",
            "obsnm": "담양1조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "5001701",
            "obsnm": "담양홍수조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        null,
        {
            "dmobscd": "5002410",
            "obsnm": "장성댐",
            "agcnm": "한국농어촌공사",
            "addr": "전라남도 장성군",
            "etcaddr": "장성읍 용강리 취수탑",
            "lon": "126-49-10",
            "lat": "35-21-34 ",
            "pfh": "90.95",
            "fldlmtwl": "90",
            "links": []
        },
        {
            "dmobscd": "5003410",
            "obsnm": "나주댐",
            "agcnm": "한국농어촌공사",
            "addr": "전라남도 나주시",
            "etcaddr": "다도면 판촌리 취수탑 도교",
            "lon": "126-51-38",
            "lat": "34-57-30 ",
            "pfh": "68.03",
            "fldlmtwl": "64.9",
            "links": []
        },
        {
            "dmobscd": "5003619",
            "obsnm": "화순1조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "5003630",
            "obsnm": "화순2조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        {
            "dmobscd": "5003701",
            "obsnm": "화순홍수조절지",
            "agcnm": "한국수자원공사",
            "addr": " ",
            "etcaddr": " ",
            "lon": " ",
            "lat": " ",
            "pfh": " ",
            "fldlmtwl": " ",
            "links": []
        },
        null,
        {
            "dmobscd": "5101110",
            "obsnm": "장흥댐",
            "agcnm": "한국수자원공사",
            "addr": "전라남도 장흥군",
            "etcaddr": "부산면 지천리",
            "lon": "126-53-07",
            "lat": "34-45-02 ",
            "pfh": "82.8",
            "fldlmtwl": "79",
            "links": []
        }
    ]
}
